# Favicon
favicon: /favicon.ico

# SEO
keywords: blog, xiongwe, wuhan, software engineer, rant, seattle, coding, interview

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /blog
  Twitter: https://twitter.com/1812_boren
  # Weibo: https://www.weibo.com/romanchelsea
  # Zhihu: https://www.zhihu.com/people/romanchelsea
  About: /about

# Nav menu
menu:
  Home: /
  Blog: /blog
  About: /about
